from typing import Protocol, Sequence, Optional
from datetime import datetime

class UserRepository(Protocol):
    def create(self, username: str, email: str, posts_count: int) -> dict: ...
    def list_with_posts(self, offset: int, limit: int) -> tuple[int, list[dict]]: ...

class PostRepository(Protocol):
    def create(self, user_id: int, content: str) -> dict: ...
    def like(self, post_id: int) -> Optional[dict]: ...
    def list_feed(self, offset: int, limit: int) -> tuple[int, list[dict]]: ...
